/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IonApp: typeof import('@ionic/vue')['IonApp']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonCard: typeof import('@ionic/vue')['IonCard']
    IonCardTitle: typeof import('@ionic/vue')['IonCardTitle']
    IonCol: typeof import('@ionic/vue')['IonCol']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonFooter: typeof import('@ionic/vue')['IonFooter']
    IonGrid: typeof import('@ionic/vue')['IonGrid']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonIcon: typeof import('@ionic/vue')['IonIcon']
    IonImg: typeof import('@ionic/vue')['IonImg']
    IonItem: typeof import('@ionic/vue')['IonItem']
    IonLabel: typeof import('@ionic/vue')['IonLabel']
    IonList: typeof import('@ionic/vue')['IonList']
    IonRow: typeof import('@ionic/vue')['IonRow']
    IonText: typeof import('@ionic/vue')['IonText']
    IonTitle: typeof import('@ionic/vue')['IonTitle']
    IonToolbar: typeof import('@ionic/vue')['IonToolbar']
    MusicButton: typeof import('./src/components/MusicButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
